### ISSUE TITLE
when i run the example

### ISSUE THREAD

**Issue by Yanthirteen13** [ViennaTools/ViennaPS#67]
he@he-virtual-machine:~/ViennaPS/build/ViennaPS/examples/holeEtching$ python3 holeEtching.py config.txt
Running 2D simulation.
Traceback (most recent call last):
  File "/home/he/ViennaPS/build/ViennaPS/examples/holeEtching/holeEtching.py", line 12, in <module>
    import viennaps2d as vps
  File "/home/he/.local/lib/python3.10/site-packages/viennaps2d/__init__.py", line 11, in <module>
    from ._viennaps2d import *
ImportError: libvtkIOXMLParser.so.1: cannot open shared object file: No such file or directory

can u help me?i dont know what's the problem,thanks a lot

**Comment by tobre1** [comment]
It appears there might be a linking issue with your VTK build. Could you please clarify whether you are using your own custom-built VTK, or if you're relying on the VTK build through buildDependencies while setting up ViennaPS?

**Comment by Yanthirteen13** [comment]
i am relying on the VTK build through buildDependencies while setting up ViennaPS

**Comment by tobre1** [comment]
I am not able to reproduce this problem. Could you please provide additional information on your build system and building steps.

**Comment by Curve** [comment]
With the latest CMake overhaul this should now work.

Could you please update and test again?

**Comment by tobre1** [comment]
I’ll close this issue due to inactivity.
If you still encounter the problem, feel free to reopen it.
